services:
  app:
    image: node:20-alpine
    container_name: biterush-nextjs-jenkins
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "3001:3000" 
    environment:
      - MONGODB_URI=mongodb://db:27017/biterush
      - JWT_SECRET=br_secret_8f92a1b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t
      - ADMIN_EMAIL=admin@biterush.pk
      - ADMIN_PASSWORD=Admin@123
      - COOKIE_SECURE=false
      - PORT=3000
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - biterush-network

  db:
    image: mongo:latest
    container_name: biterush-mongodb-jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_jenkins:/data/db
    restart: unless-stopped
    networks:
      - biterush-network

networks:
  biterush-network:
    driver: bridge

volumes:
  mongodb_data_jenkins: